### ISSUE TITLE
API 7 Status?

### ISSUE THREAD

**Issue by AnZaNaMa** [Time6628/Market#10]
Hey sorry to bother you. I'm just curious what the current status on the API 7 update is. I see that you have a branch for API 7 going and I'm just curious what the status on that update is. Currently, there aren't any good shop plugins out for API 7 and I'd love to see one.

**Comment by Time6628** [comment]
It's already been updated.

**Comment by Time6628** [comment]
http://jenkins.timethecat.pw:8080/job/Market/25/

**Comment by AnZaNaMa** [comment]
thank you. Didn't find a link to the CI anywhere on the Sponge page or github
