### ISSUE TITLE
[Request] HuskyUI Support for API 7 branch

### ISSUE THREAD

**Issue by AnZaNaMa** [Time6628/Market#11]
Looks like HuskyUI is up to date and I'm not sure how difficult it would be to add support for it back into the API 7 branch. Would be great to have though.

**Comment by AnZaNaMa** [comment]
So, not even a response? Like, "this is on my to do list" or "I'm not going to be reimplementing this" or "it already works, you idiot"?

**Comment by Time6628** [comment]
The api7 branch is a fork of the stable version of market. If you want huskyui with api7, compile the dbsandinv branch yourself.
