### ISSUE TITLE
sponge 1.10.2 2477 ,5 api ? 

### ISSUE THREAD

**Issue by Lajtmen** [Time6628/Market#13]
sponge 1.10.2 2477 ,5 api ?  is it working ?

**Comment by Time6628** [comment]
Yes.

**Comment by Lajtmen** [comment]
The thing is ,,, when i put it on the server and i type /market or something its says that command isnt  avaliable. So it doesnt working

**Comment by Time6628** [comment]
Because you need a database.

**Comment by Lajtmen** [comment]
Can you please explain me what is it ? :D or how to add it ? Thank you for your patiance :D
