### ISSUE TITLE
Null Pointer causing Issues in Experimental Sponge builds

### ISSUE THREAD

**Issue by pinkphoenix1990** [Time6628/Market#3]
**Hey**

I just wanted to give a quick heads up about the error I'm receiving on my Beta Sponge server. I haven't checked it out on any other version just yet, but I am sure they are working just fine. I'll paste the code that my console spits out to me below and, just in-case you didn't know this, you're totally awesome for making this amazing plugin on Sponge! Keep it up!

16.07 20:58:55 [Server] ERROR [Sponge]: Could not pass ClientConnectionEvent$Join$Impl to Plugin{id=market, name=Market, version=0.2.1, description=Market, url=https://kookykraftmc.net, authors=[TimeTheCat], source=mods/Market-0.2.1.jar} 16.07 20:58:55 [Server] INFO java.lang.NullPointerException: null 16.07 20:58:55 [Server] INFO at com.kookykraftmc.market.Market.onPlayerJoin(Market.java:251) ~[Market.class:?] 16.07 20:58:55 [Server] INFO at org.spongepowered.common.event.listener.JoinListener_Market_onPlayerJoin4.handle(Unknown Source) ~[?:?] 16.07 20:58:55 [Server] INFO at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12-7.0.0-BETA-300] 16.07 20:58:55 [Server] INFO at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:349) [SpongeEventManager.class:1.12-7.0.0-BETA-300] 16.07 20:58:55 [Server] INFO at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:366) [SpongeEventManager.class:1.12-7.0.0-BETA-300] 16.07 20:58:55 [Server] INFO at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:199) [SpongeImpl.class:1.12-7.0.0-BETA-300] 16.07 20:58:55 [Server] INFO at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(SourceFile:1442) [pj.class:?] 16.07 20:58:55 [Server] INFO at net.minecraft.server.management.PlayerList.func_72355_a(SourceFile:1209) [pj.class:?] 16.07 20:58:55 [Server] INFO at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(SourceFile:119) [pa.class:?] 16.07 20:58:55 [Server] INFO at net.minecraft.server.network.NetHandlerLoginServer.func_73660_a(SourceFile:66) [pa.class:?] 16.07 20:58:55 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(SourceFile:231) [gw.class:?] 16.07 20:58:55 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(SourceFile:187) [ox.class:?] 16.07 20:58:55 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:1600) [MinecraftServer.class:?] 16.07 20:58:55 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:343) [nx.class:?] 16.07 20:58:55 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:560) [MinecraftServer.class:?] 16.07 20:58:55 [Server] INFO at net.minecraft.server.MinecraftServer.run(SourceFile:464) [MinecraftServer.class:?] 16.07 20:58:55 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by Time6628** [comment]
You have to regen your config.
