### ISSUE TITLE
Last version doesn't load if HuskyUI is not installed

### ISSUE THREAD

**Issue by kaal-1** [Time6628/Market#5]
It works fine with HuskyUI, but the players are able to steal items (including the barrier) inside the UI, so I've decided to remove it and leave it to be chat-only. No such luck, since it is not working: https://hastebin.com/fokinaxeno.swift

**Comment by Time6628** [comment]
Fixed: http://jenkins.timethecat.pw:8080/job/Market/14/artifact/build/libs/Market-0.2.4.jar
