### ISSUE TITLE
Easy Fix to make it API5 Compatible

### ISSUE THREAD

**Issue by Auroratic** [Time6628/Market#8]
Found out its (almost) compatible! When using HuskyUI, and clicking on the Market to purchase the item, it spits out the item from the player as a duping mechanism instead of click to prompt Buy or QuickBuy in Chat.

Can this be easily fixed so it could be used with API 5 aswell :)

**Comment by Time6628** [comment]
The plugin is fully API 5 compatible. The HuskyUI part is currently still in development and will be fixed soon.

**Comment by Auroratic** [comment]
Thanks! Watching this project. Looking forward for the HuskyUI Fix soon :)
