### ISSUE TITLE
MySQL Support consideration and Sell orders and maybe Info permissions.

### ISSUE THREAD

**Issue by KaneHart** [Time6628/Market#9]
Hello this is more of a request ticket. I'm hoping to see a few options and even if it's not now but way down the road I'm always on the lookout for long term support for other servers.

Right now I'm using 1.10.2.

First off I like to see MySQL support if possible. I'm more comfortable with it and have better how to with working on it. My servers will never have 10,000 items listed so if it's a slight performance head I'm not too worried. I had used a older version and upgraded and lot my data and this alone has made me a bit tense using a unknown database software.

I like to see also a Sell orders added if I got it right there and not backwards. Same idea even make the player require the item in their hand but the idea is you can request to buy certain goods for a certain price. We find that most vet players want to buy and we find most new players want to sell. The issue is that the vet players don't want to really spend time going to tiny shops but rather have it in larger orders. Downside with this system is you need some sort of buffer so when the user has someone sell them a few items that the person will need a command to grab the items?

The last thing and I'm not sure the term for this so please correct me. It's something I'm seeing more and more for sponge permission plugins and I love it a lot. I like to see a max sell/buy orders info permission. This way a player can't list 10000 items but limited to say 10 at one time.

Thanks so much for your time, Time! I know you been a big help in the past with the community when it came to modded/plugin API stuff in the past. 

Remember these are suggestions and if you have any reasons not to accept some or all there is not hard feelings I rather just be frank upfront so I'm not waiting down the road for nothing :)

**Comment by Time6628** [comment]
MySQL will not be implemented.

I'll look into sell orders.

Max items is already in the works.

**Comment by KaneHart** [comment]
Thanks for your considerations.
